CREATE TABLE AUTHOR
(
    ID varchar(36) PRIMARY KEY NOT NULL,
    NAME varchar(255) NOT NULL
);
CREATE UNIQUE INDEX AUTHOR_ID_uindex ON AUTHOR (ID);
ALTER TABLE AUTHOR COMMENT = 'Автор';

CREATE TABLE GENRE
(
    ID varchar(36) PRIMARY KEY NOT NULL,
    NAME varchar(255) NOT NULL
);
CREATE UNIQUE INDEX GENRE_ID_uindex ON GENRE (ID);
ALTER TABLE GENRE COMMENT = 'Жанр';

CREATE TABLE BOOK
(
    ID varchar(36) PRIMARY KEY NOT NULL,
    NAME varchar(255) NOT NULL
);
CREATE UNIQUE INDEX BOOK_ID_uindex ON BOOK (ID);
ALTER TABLE BOOK COMMENT = 'Книга';

CREATE TABLE BOOK_TO_AUTHOR
(
    ID varchar(36) PRIMARY KEY NOT NULL,
    BOOK_ID varchar(36) NOT NULL,
    AUTHOR_ID varchar(36) NOT NULL,
    CONSTRAINT FK_BOOK_T_BOOK_TO_AUT FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID),
    CONSTRAINT FK_AUTHOR_T_BOOK_TO_AUT FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID)
);
CREATE UNIQUE INDEX BOOK_TO_AUTHOR_ID_uindex ON BOOK_TO_AUTHOR (ID);

CREATE TABLE BOOK_TO_GENRE
(
    ID varchar(36) PRIMARY KEY NOT NULL,
    BOOK_ID varchar(36) NOT NULL,
    GENRE_ID varchar(36) NOT NULL,
    CONSTRAINT FK_BOOK_T_BOOK_TO_GENRE FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID),
    CONSTRAINT FK_GENRE_T_BOOK_TO_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID)
);
CREATE UNIQUE INDEX BOOK_TO_GENRE_ID_uindex ON BOOK_TO_GENRE (ID);

CREATE TABLE COMMENTARY
(
    ID varchar(36) PRIMARY KEY NOT NULL,
    MESSAGE varchar(1000) NOT NULL,
    BOOK_ID varchar(36) NOT NULL,
    CONSTRAINT FK_COMMENT_T_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);
CREATE UNIQUE INDEX COMMENTERY_ID_uindex ON COMMENTARY (ID);
ALTER TABLE COMMENTARY COMMENT = 'Коментарий';