#server:
#  port: 8082
#  session:
#    cookie:
#      name: UISESSION
#
#security:
#  oauth2:
#    client:
#      registration:
#        custom-client:
#          client-id: auth-service
#          client-secret: my-secret-key
#          client-name: Auth Server
#          scope: user_info
#          provider: custom-provider
#          redirect-uri: http://localhost:8082/login/oauth2/code/
#          client-authentication-method: basic
#          authorization-grant-type: authorization_code
#      provider:
#        custom-provider:
#          token-uri: http://localhost:8081/auth/oauth/token
#          authorization-uri: http://localhost:8081/auth/oauth/authorize
#          user-info-uri: http://localhost:8081/auth/user/me
#          user-name-attribute: name
#spring:
#  thymeleaf:
#    cache: false

server:
  port: 8082
  servlet:
    context-path: /ui
  session:
    cookie:
      name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me
spring:
  thymeleaf:
    cache: false
