spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

hibernate:
  show_sql: true
  format_sql: true
  ejb:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy