DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE BOOK(ID INT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GENRE(ID INT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE AUTHOR(ID INT PRIMARY KEY, NAME VARCHAR(255));
